version: '3'
services:
  api:
    image: 'golang:1.19.4-alpine'
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    ports:
      - '9000:9000'
    depends_on:
      - db
    networks:
      - todo-go
    restart: unless-stopped

  db:
    image: 'postgres:alpine'
    environment:
      POSTGRES_PASSWORD: '1122'
      POSTGRES_USER: 'user_todo'
      POSTGRES_DB: 'api_postgres_go'
    ports:
      - '5432:5432'
    networks:
      - todo-go
    restart: unless-stopped

networks:
  todo-go:
